using Core;
using Core.Model;
using Xunit;

namespace Tests {
    public class TestGeneratorTests {
        [Fact]
        public void ShouldCreateValidXUnitTestClass() {
            var generator = new TestGenerator();
            var classInfo = new ClassInfo {
                Namespace = "MyNamespace",
                Name = "Calculator",
                PublicMethods = {
                    new MethodInfo {
                        Name = "Add",
                        ReturnType = "int",
                        Parameters = {
                            new ParameterInfo { Name = "a", Type = "int" },
                            new ParameterInfo { Name = "b", Type = "int" }
                        }
                    }
                }
            };

            var result = generator.Generate(classInfo, new List<string>());

            Assert.Contains("using Xunit;", result);
            Assert.Contains("namespace MyNamespace.Tests", result);
            Assert.Contains("public class CalculatorTests", result);
            Assert.Contains("[Fact]", result);
            Assert.Contains("public void AddTest()", result);
            Assert.Contains("Assert.Fail(\"autogenerated\");", result);
        }

        [Fact]
        public void ShouldCreateMockFields() {
            var generator = new TestGenerator();
            var classInfo = new ClassInfo {
                Namespace = "MyNamespace",
                Name = "Service",
                HasInterfaceDependencies = true,
                ConstructorParameters = {
                    new ConstructorParameterInfo {
                        Name = "repository",
                        Type = "IRepository",
                        IsInterface = true
                    },
                    new ConstructorParameterInfo {
                        Name = "logger",
                        Type = "ILogger",
                        IsInterface = true
                    }
                },
                PublicMethods = {
                    new MethodInfo {
                        Name = "GetData",
                        ReturnType = "string",
                        Parameters = { }
                    }
                }
            };

            var result = generator.Generate(classInfo, new List<string>());

            Assert.Contains("using Moq;", result);
            Assert.Contains("private Mock<IRepository> _repository;", result);
            Assert.Contains("private Mock<ILogger> _logger;", result);
            Assert.Contains("_repository = new Mock<IRepository>();", result);
            Assert.Contains("_logger = new Mock<ILogger>();", result);
            Assert.Contains("_serviceUnderTest = new Service(_repository.Object, _logger.Object);", result);
            Assert.Contains("Assert.Equal(expected, actual);", result);
        }

        [Fact]
        public void ShouldGenerateUniqueNamesForOverloadedMethods() {
            var generator = new TestGenerator();
            var classInfo = new ClassInfo {
                Namespace = "MyNamespace",
                Name = "OverloadedClass",
                PublicMethods = {
                    new MethodInfo { Name = "Method", ReturnType = "void", Parameters =
                        new List<ParameterInfo> {
                            new ParameterInfo { Name = "value", Type = "int" }
                        }
                    },
                    new MethodInfo { Name = "Method", ReturnType = "void", Parameters =
                        new List<ParameterInfo> {
                            new ParameterInfo { Name = "value", Type = "string" }
                        }
                    },
                    new MethodInfo { Name = "Method", ReturnType = "void", Parameters =
                        new List<ParameterInfo> {
                            new ParameterInfo { Name = "value", Type = "double" }
                        }
                    }
                }
            };

            var result = generator.Generate(classInfo, new List<string>());

            Assert.Contains("public void Method1Test()", result);
            Assert.Contains("public void Method2Test()", result);
            Assert.Contains("public void Method3Test()", result);
        }

        [Fact]
        public void ShouldIncludeOriginalUsings() {
            var generator = new TestGenerator();
            var classInfo = new ClassInfo {
                Namespace = "MyNamespace",
                Name = "Calculator",
                PublicMethods = { new MethodInfo { Name = "Add", ReturnType = "int" } }
            };
            var originalUsings = new List<string>() {
                "System.Collections.Generic",
                "MyProject.Models",
                "MyProject.Services"
            };

            var result = generator.Generate(classInfo, originalUsings);

            Assert.Contains("using System.Collections.Generic;", result);
            Assert.Contains("using MyProject.Models;", result);
            Assert.Contains("using MyProject.Services;", result);
            Assert.Contains("using MyNamespace;", result);
            Assert.Contains("using Xunit;", result);
        }
    }
}
